name: Feature request
description: Request a new feature
labels: ["type: feature"]
body:
  - type: markdown
    attributes:
      value: |
        If you have a technical feature you'd like to see added, please fill out the form below. If you're able to submit a PR, that's even better! Thanks for contributing!
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: A clear and concise description of the feature. If you intend to submit a PR for this feature, tell us how in the description. Thanks!
      placeholder: Feature description
    validations:
      required: true
