name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      # run any `bun` or `bun x` command
      - run: bun check
      - run: bun check:types
