name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Format/Lint
        run: bun check

      - name: Check TS Types
        run: bun check:types
